(defsketch app ((copy-pixels t) (y-axis :up)
                (j 100)
                (i 0)
                (dir 1)
                (cx 500)
                (cy 500)
                (r 70)
                (rad 35))
#+nil  (setf i 1 j 1)
  (with-pen (make-pen :fill (rgb 0.3 0.7 0.4 1/20))
    (rect 0 0 width height))
  (with-pen (make-pen :fill (rgb 0.2 0.3 0.5))
    (circle cx cy 10)
   (let ((cx cx) (cy cy))
     (incf cx (* 2 r (cos (radians i))))
     (incf cy (* 2 r (sin (radians i))))
     (circle cx cy 10)))
  (when (< (decf j 1) 0)
    (incf cx (* 2 r (cos (radians i))))
    (incf cy (* 2 r (sin (radians i))))
    (setf i (+ 180 i)
          j (random 360)
          dir (- dir)))
  (translate cx cy)
  (rotate (incf i dir))
  (with-pen (make-pen :stroke (rgb 0.5 0.1 0.2 1))
    (circle r 0 rad)
    (circle (+ r 7) (* dir 11) 3)
    (circle (- r 6) (* dir 12) 3)))
